services:
  viewAgent:
    image: python:3.10-slim  
    container_name: viewAgent
    working_dir: /app
    volumes:
      - ./viewAgent:/app  
    ports:
      - "5005:5005"  
    networks:
      - MARS_Network
    command: >
      sh -c "pip install -r requirements.txt && python viewAgent.py"

  controlAgent:
    image: python:3.10-slim
    container_name: controlAgent
    working_dir: /app
    volumes:
      - ./controlAgent:/app
    networks:
      - MARS_Network
    command: >
      sh -c "pip install -r requirements.txt && python controlAgent.py"

  RADAgent:
    image: python:3.10-slim
    container_name: RADAgent
    working_dir: /app
    volumes:
      - ./RADAgent:/app
    networks:
      - MARS_Network
    command: >
      sh -c "pip install -r requirements.txt && python retrievalAndDatabaseAgent.py"

  generationAgent:
    image: python:3.10-slim
    container_name: generationAgent
    working_dir: /app
    volumes:
      - ./generationAgent:/app
    networks:
      - MARS_Network
    command: >
      sh -c "pip install -r requirements.txt && python generationAgent.py"

networks:
  MARS_Network:
    driver: bridge
